### ISSUE TITLE
Suportar layout Pessoa Física (layouts de reporte individual)

### ISSUE THREAD

**Issue by luizParreira** [Biscoint/exchanges-rfb#6]
Estou tentando fazer o upload do arquivo para a receita utilizando essa lib, mas estou recebendo o seguinte erro:

![image](https://user-images.githubusercontent.com/8305710/94747450-50f0e480-0355-11eb-8c2e-de7714bca556.png)

Procurei na internet um novo leiaute para atualizar o arquivo, mas não consegui achar. Vocês sabem alguma coisa sobre? 🤔

Obrigado :)

**Comment by augustresende** [comment]
@luizParreira, no momento o exchanges-rfb só faz o layout de Exchanges com CNPJ, não funciona pra pessoa física ainda.

**Comment by luizParreira** [comment]
@AugustoResende Eu estou enviando os dados da https://bipa.app, não é pessoa física. Parece que eles mudaram as validações para o arquivo de pessoa jurídica tbm. 🤔

**Comment by luizParreira** [comment]
Hahaha eu estava selecionando um campo errado, my bad 😅   

Consegui enviar aqui, se quiser fechar a issue pode fechar. :)
